/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BOVisual.Login;

import BOVisual.BackOfficeGen;
import db.Database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.dao.BO.EmployeeDAO;
import model.dao.DatabaseException;
import model.entity.BO.Employee;

/**
 *
 * @author Cy
 */
public class LogIn extends javax.swing.JFrame {
    
    
    int xMouse;
    int yMouse;

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        description = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        connect = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BackOffice BookShooop!!!");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(499, 449));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        description.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.selectionBackground"));
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 300, 60));

        header.setToolTipText("");
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 50));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOVisual/Login/Close X (Custom) (Custom).png"))); // NOI18N
        exit.setText("exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 50, 50));

        connect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOVisual/Login/button large.png"))); // NOI18N
        connect.setText("connect");
        connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                connectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                connectMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                connectMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                connectMouseReleased(evt);
            }
        });
        getContentPane().add(connect, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 300, 50));

        user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user.setBorder(null);
        user.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                userMouseMoved(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 280, 40));

        password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 280, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOVisual/Login/loginBookShopBack.png"))); // NOI18N
        Background.setToolTipText("");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 450));

        setSize(new java.awt.Dimension(495, 403));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void connectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectMouseEntered
        // TODO when Mouse cursor hovers:
        ImageIcon img = new ImageIcon(getClass().getResource("button large hover.png"));
        connect.setIcon(img);
     
    }//GEN-LAST:event_connectMouseEntered

    private void connectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectMouseExited
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon(getClass().getResource("button large.png"));
        connect.setIcon(img);
        
    }//GEN-LAST:event_connectMouseExited

    private void connectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectMousePressed
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon(getClass().getResource("button large pressed.png"));
        connect.setIcon(img);
    }//GEN-LAST:event_connectMousePressed

    private void connectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectMouseReleased
        ImageIcon img = new ImageIcon(getClass().getResource("button large hover.png"));
        connect.setIcon(img);
    }//GEN-LAST:event_connectMouseReleased

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        
       System.exit(0);
       
    }//GEN-LAST:event_exitMouseClicked
//Code here bellow to Move window with mouse: ---- START ------ 
    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
    int x = evt.getXOnScreen();
    int y = evt.getYOnScreen();
    this.setLocation(x - xMouse , y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY(); 
    }//GEN-LAST:event_headerMousePressed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void userMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseMoved
        // Code here to announce what it is that needs to be filled :
    }//GEN-LAST:event_userMouseMoved

    private void connectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectMouseClicked
/** 
 *  Login Check
 */
   String login = user.getText();
   String pass = password.getText();
    // 
   
            Employee ep = new Employee();
            ep.setEmployeeLogin(login);
            System.out.println("Employee: " + login);
            if (pass == null){
                System.out.println("Password is null!");
            } else {
                System.out.println("Password entered!");
            }
            ep.setEmployeePassword(pass);
            EmployeeDAO epDAO = new EmployeeDAO();
        try {
            Employee epCheck = epDAO.getLogin(ep);
            System.out.println(epCheck);
            if (epCheck.getEmployeeLogin() != null){
                System.out.println("Employee exists!");
/**
 * 
 * INSERT HERE THE FRAME TO START THE APPLICATION WHEN LOGIN SUCCESFULL!!!!
 * 
 */                
                BackOfficeGen log = new BackOfficeGen();
                dispose();
/**
 * End INSERT HERE, add jframe above!
 */
            } else{
                System.out.println("Employee invalid");       
                        }
        } catch (DatabaseException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }                // TODO add your handling code here:
    }//GEN-LAST:event_connectMouseClicked
// CODE here above to Move window with mouse: ----- STOP -------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel connect;
    private javax.swing.JLabel description;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel header;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
